name: Python Package using Conda

on:
  push:
    tags:
      - v*

jobs:
  build-linux:
    runs-on: ubuntu-latest
    environment: pypi_test_api
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Upgrading build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
        python -m pip install --upgrade build
    - name: Building ...
      run: |
        python -m build
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: | 
          dist/paddle-*.whl
          dist/paddle-*.tar.gz
